# Base: https://github.com/l7mp/rtpengine-k8s-l7mp-test/blob/master/kubernetes/rtpengine-worker.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: l7mp-worker-config
data:
  l7mp-worker.yaml: |
    # Controller listening on 1234, plus some useful debug clusters
    admin:
      log_level: info
      log_file: stdout
      access_log_path: /tmp/admin_access.log
    listeners:
      - name: controller-listener
        spec: { protocol: HTTP, port: 1234 }
        rules:
          - action:
              route:
                destination:
                  spec: { protocol: L7mpController }
    clusters:
      - name: ingress-metric-counter
        spec: { protocol: Metric }
      - name: egress-metric-counter
        spec: { protocol: Metric }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rtpengine-config
  namespace: default
data:
  rtpengine.conf: |
    [rtpengine]
    # access only via the sidecar proxy
    # listen-ng=MY_IP:22222
    # interface=MY_IP
    # listen-tcp=127.0.0.1:22223
    listen-ng=127.0.0.1:22222
    interface=127.0.0.1

    foreground=true
    log-stderr=true

    port-min=10000
    port-max=20000

    # recording-dir=/tmp
    # recording-method=pcap
    # recording-format=eth

    log-level=7
    delete-delay=0

    timeout=600

    redis = redis:6379/1
    subscribe-keyspace=1
    # redis-write = password@12.23.34.45:6379/42
    # redis-num-threads = 8
    # no-redis-required = false
    # redis-expires = 86400
    # redis-allowed-errors = -1
    # redis-disable-time = 10
    # redis-cmd-timeout = 0
    # redis-connect-timeout = 1000

    # sip-source = false
    # dtls-passive = false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    notify-keyspace-events KEA
---
apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: ws-worker-rtpengine-ng
spec:
  selector:
    matchLabels:
      app: l7mp-worker
  listener:
    spec:
      WebSocket:
        port: 22222
    rules:
      - action:
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/ws-worker-rtpengine-ng-target
          # rewrite:
          #   - path: "HTTP/headers/sec-websocket-protocol"
          #     valueStr: "ng.rtpengine.com"
          #   - path: "HTTP/headers/sec-websocket-key"
          #     valueStr: " "
          #   - path: "HTTP/headers/host"
          #     valueStr: " "
---
apiVersion: l7mp.io/v1
kind: Target
metadata:
  name: ws-worker-rtpengine-ng-target
spec:
  selector:
    matchLabels:
      app: l7mp-worker
  cluster:
    spec:
      UDP:
        port: 22222
    endpoints:
      - { spec: { address: "127.0.0.1" } }
---
apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: ws-ingress-rtpengine-controller
spec:
  selector:
    matchLabels:
      app: l7mp-ingress
  listener:
    spec:
      WebSocket:
        port: 2000
    rules:
      - action:
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/ws-ingress-rtpengine-controller-target
          # rewrite:
          #   - path: "HTTP/headers/sec-websocket-protocol"
          #     valueStr: " "
          #   - path: "HTTP/headers/sec-websocket-key"
          #     valueStr: " "
          #   - path: "HTTP/headers/host"
          #     valueStr: " "
---
apiVersion: l7mp.io/v1
kind: Target
metadata:
  name: ws-ingress-rtpengine-controller-target
spec:
  selector:
    matchLabels:
      app: l7mp-ingress
  cluster:
    spec:
      WebSocket:
        port: 2000
    endpoints:
      - selector:
          matchLabels:
            app: rtpe-controller
---
apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: ws-worker-rtpengine-controller
spec:
  selector:
    matchLabels:
      app: rtpe-controller
  listener:
    spec:
      WebSocket:
        port: 2000
    rules:
      - action:
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/ws-worker-rtpengine-controller-target
          # rewrite:
          #   - path: "HTTP/headers/sec-websocket-protocol"
          #     valueStr: " "
          #   - path: "HTTP/headers/sec-websocket-key"
          #     valueStr: " "
          #   - path: "HTTP/headers/host"
          #     valueStr: " "
---
apiVersion: l7mp.io/v1
kind: Target
metadata:
  name: ws-worker-rtpengine-controller-target
spec:
  selector:
    matchLabels:
      app: rtpe-controller
  cluster:
    spec:
      WebSocket:
        port: 1999
    endpoints:
      - { spec: { address: "127.0.0.1" } }
