# Base: https://github.com/l7mp/rtpengine-k8s-l7mp-test/blob/master/kubernetes/rtpengine-worker.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: l7mp-worker-config
data:
  l7mp-worker.yaml: |
    # Controller listening on 1234, plus some useful debug clusters
    admin:
      log_level: info
      log_file: stdout
      access_log_path: /tmp/admin_access.log
    listeners:
      - name: controller-listener
        spec: { protocol: HTTP, port: 1234 }
        rules:
          - action:
              route:
                destination:
                  spec: { protocol: L7mpController }
    clusters:
      - name: ingress-metric-counter
        spec: { protocol: Metric }
      - name: egress-metric-counter
        spec: { protocol: Metric }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rtpengine-config
  namespace: default
data:
  rtpengine.conf: |
    [rtpengine]
    # access only via the sidecar proxy
    # listen-ng=MY_IP:22222
    # interface=MY_IP
    listen-ng=127.0.0.1:22222
    interface=lo

    foreground=true
    log-stderr=true

    port-min=10000
    port-max=20000

    recording-dir=/tmp
    recording-method=pcap
    recording-format=eth

    log-level=7
    delete-delay=0

    timeout=600

    # redis = 127.0.0.1:6379/5
    # redis-write = password@12.23.34.45:6379/42
    # redis-num-threads = 8
    # no-redis-required = false
    # redis-expires = 86400
    # redis-allowed-errors = -1
    # redis-disable-time = 10
    # redis-cmd-timeout = 0
    # redis-connect-timeout = 1000

    # sip-source = false
    # dtls-passive = false
---
# rtpe-operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtpe-operator
  labels:
    app: rtpe-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtpe-operator
  template:
    metadata:
      labels:
        app: rtpe-operator
    spec:
      volumes:
        - name: l7mp-config-volume
          configMap:
            name: l7mp-worker-config
      containers:
        - name: l7mp
          image: l7mp/l7mp:latest
          imagePullPolicy: IfNotPresent
          command: [ "node" ]
          args: [ "l7mp-proxy.js", "-c", "config/l7mp-worker.yaml", "-s", "-l", "info" ]
          ports:
          - containerPort: 1234
          volumeMounts:
            - name: l7mp-config-volume
              mountPath: /app/config
        - name: net-debug
          image: l7mp/net-debug:0.5.3
        - name: rtpe-operator
          image: rtpe-operator
          imagePullPolicy: Never
          env:
            - name: RTPE_OPERATOR
              value: "l7mp"
            - name: RTPE_ADDRESS
              value: "l7mp-worker"
            - name: RTPE_PORT
              value: "22222"
            - name: WITHOUT_JSONSOCKET
              value: "yes"
---
# l7mp-worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: l7mp-worker
  labels:
    app: l7mp-worker
spec:
  # replicas: 2
  replicas: 1
  selector:
    matchLabels:
      app: l7mp-worker
  template:
    metadata:
      labels:
        app: l7mp-worker
    spec:
      volumes:
        - name: l7mp-config-volume
          configMap:
            name: l7mp-worker-config
        - name: rtpengine-config-volume
          configMap:
            name: rtpengine-config
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
      containers:
      # sidecar
      - name: l7mp
        image: l7mp/l7mp:latest
        imagePullPolicy: IfNotPresent
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do echo hello; sleep 10;done"]
        command: [ "node" ]
        args: [ "l7mp-proxy.js", "-c", "config/l7mp-worker.yaml", "-s", "-l", "info" ]
        ports:
        - containerPort: 1234
        volumeMounts:
          - name: l7mp-config-volume
            mountPath: /app/config
      - name: net-debug
        image: l7mp/net-debug:0.5.3
      - name: rtpengine
        image: drachtio/rtpengine
        imagePullPolicy: IfNotPresent
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do echo hello; sleep 10;done"]
        command: [ "/usr/local/bin/rtpengine" ]
        args: [ "--config-file=/etc/rtpengine/rtpengine.conf", "-i", "lo", "-f", "-L", "7", "-E" ]
        volumeMounts:
          - name: rtpengine-config-volume
            mountPath: /etc/rtpengine
---
# l7mp-worker-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: l7mp-worker
  name: l7mp-worker
spec:
  ports:
  - port: 1234
    name: http-control-port
    protocol: TCP
    targetPort: 1234
  - port: 22222
    name: udp-rtpengine-ng-port
    protocol: UDP
    targetPort: 22222
  - port: 2000
    name: rtpe-operator-port
    protocol: UDP
    targetPort: 2000
  selector:
    app: l7mp-worker
  type: ClusterIP
---
# rtpe-operator-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rtpe-operator-service
  name: rtpe-operator-service
spec:
  ports:
  - port: 1234
    name: http-control-port
    protocol: TCP
    targetPort: 1234
  - port: 2000
    name: rtpe-operator-port
    protocol: UDP
    targetPort: 2000
  selector:
    app: rtpe-operator
  type: ClusterIP
---
# rtpengine-ng
apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: udp-ingress-rtpengine-ng
spec:
  selector:
    matchLabels:
      app: l7mp-ingress
  listener:
    spec:
      UDP:
        port: 22222
    rules:
      - action:
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/udp-ingress-rtpengine-ng-target

---

apiVersion: l7mp.io/v1
kind: Target
metadata:
  name: udp-ingress-rtpengine-ng-target
spec:
  selector:
    matchLabels:
      app: l7mp-ingress
  cluster:
    spec: 
      UDP:
        port: 22222
    endpoints:
      - selector:
          matchLabels:
            app: l7mp-worker

---

apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: udp-worker-rtpengine-ng
spec:
  selector:
    matchLabels:
      app: l7mp-worker
  listener:
    spec:
      UDP:
        port: 22222
    rules:
      - action:
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/udp-worker-rtpengine-ng-target

---

apiVersion: l7mp.io/v1
kind: Target
metadata:
  name: udp-worker-rtpengine-ng-target
spec:
  selector:
    matchLabels:
      app: l7mp-worker
  cluster:
    spec: 
      UDP:
        port: 22222
    endpoints:
      - { spec: { address: "127.0.0.1" } }

---
apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: udp-ingress-rtpengine-operator
spec:
  selector:
    matchLabels:
      app: l7mp-ingress
  listener:
    spec:
      UDP:
        port: 2000
    rules:
      - action:
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/udp-ingress-rtpengine-operator-target

---

apiVersion: l7mp.io/v1
kind: Target
metadata:
  name: udp-ingress-rtpengine-operator-target
spec:
  selector:
    matchLabels:
      app: l7mp-ingress
  cluster:
    spec: 
      UDP:
        port: 2000
    endpoints:
      - selector:
          matchLabels:
            app: rtpe-operator

---

apiVersion: l7mp.io/v1
kind: VirtualService
metadata:
  name: udp-worker-rtpengine-operator
spec:
  selector:
    matchLabels:
      app: rtpe-operator
  listener:
    spec:
      UDP:
        port: 2000
    rules:
      - action:
          route:
            destinationRef: /apis/l7mp.io/v1/namespaces/default/targets/udp-worker-rtpengine-operator-target

---

apiVersion: l7mp.io/v1
kind: Target
metadata:
  name: udp-worker-rtpengine-operator-target
spec:
  selector:
    matchLabels:
      app: rtpe-operator
  cluster:
    spec: 
      UDP:
        port: 2000
    endpoints:
      - { spec: { address: "127.0.0.1" } }
