kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rtpe-operator
rules:
- apiGroups: ["l7mp.io"]
  resources: ["virtualservices", "targets", "rules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rtpe-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: rtpe-operator
  apiGroup: rbac.authorization.k8s.io